version:                   "3.1"

services:
  web:
    image:                 johnpoint/nginx
    container_name:        nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - site-lvcshu
    volumes:
      - /web/vhost:/web/vhost
      - /web/conf:/etc/nginx/conf.d
      - /web/ssl:/web/ssl
 
  mysql:
    image:                 mysql:5.7.23
    container_name:        mysql
    command:               --default-authentication-plugin=mysql_native_password
    networks:
      - site-lvcshu
    volumes:
      - /web/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: DNMP-lvcshu

networks:
  site-lvcshu:
